### ISSUE TITLE
The UUID custom field is not working with the component type

### ISSUE THREAD

**Issue by AliKdhim87** [Dulajdeshan/strapi-advanced-uuid#24]
### Required System information

- Node.js version:  v18.12.0
- Strapi version:  4.10.5

### Describe the bug

When I use the UUID custom field in the component type, I  got an error when I update, save and add new content.

```
Warning:
This attribute must be unique This attribute must be unique This attribute must be unique 
````

**Comment by Dulajdeshan** [comment]
@AliKdhim87 Thanks for reporting. I'll have a look on this.

**Comment by Dulajdeshan** [comment]
> ## Bug report
> ### Required System information
> * Node.js version:  v18.12.0
> * Strapi version:  4.10.5
> 
> ### Describe the bug
> When I use the UUID custom field in the component type, I got an error when I update, save and add new content.
> 
> ```
> Warning:
> This attribute must be unique This attribute must be unique This attribute must be unique 
> ```

@AliKdhim87 did you configure the field correctly? Can you share a screenshot of the custom field that you have configured in the custom component?

**Comment by AliKdhim87** [comment]
@Dulajdeshan Thanks for your quick response,

This is how I configured the custom field in my component

```json
{
  "collectionName": "components_components_accordions",
  "info": {
    "displayName": "accordion",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "body": {
      "type": "richtext"
    },
    "uuid": {
      "type": "customField",
      "customField": "plugin::strapi-advanced-uuid.strapi-advanced-uuid"
    }
  }
}
```

when I add a new item to the component  and the click
 the save button, then I get the error
 
<img width="1419" alt="Screenshot 2023-05-24 at 10 11 36" src="https://github.com/Dulajdeshan/strapi-advanced-uuid/assets/53454241/11f36560-ed6d-4a35-a25b-14d205bc9831">

**Comment by Dulajdeshan** [comment]
> 

@AliKdhim87 Thanks for sharing this. I was able to reproduce this issue. I am working on the fix now. I will update you with the status. Thanks.

**Comment by Dulajdeshan** [comment]
Hi @AliKdhim87 Seems like this is an issue with strapi itself, and it is still open.

Please checkout this. https://github.com/strapi/strapi/issues/12541

**Comment by AliKdhim87** [comment]
Thank you so much @Dulajdeshan for your effort, and I hope Strapi will fix this issue.

**Comment by Dulajdeshan** [comment]
Closing the issue as it depend on strapi - https://github.com/strapi/strapi/issues/12541
