### ISSUE TITLE
UUID Custom Field Returns null

### ISSUE THREAD

**Issue by bayramorhan** [Dulajdeshan/strapi-advanced-uuid#25]
It works and creating random UUID but I cannot access this uuid from anywhere in the API

**Comment by Dulajdeshan** [comment]
Hi @bayramorhan it should be working. Can you share more details about the issue.

Eg:
- `strapi` and `strapi-advanced-uuid` version that you are using
- Screenshot of the API Response
- Screenshot of your component

FYI:
This is my API response with the field
![image](https://github.com/Dulajdeshan/strapi-advanced-uuid/assets/38158937/eb5bb0c2-3e0f-4cb9-88c9-72216ebc27ef)

**Comment by topovik** [comment]
UUID field added to user schema
When calling the http://localhost:1337/api/auth/local/register method
data is coming, however field UUID = null
If a new uuid is generated in the created record, then the field is correctly displayed in the response to the request
