### ISSUE TITLE
Admin panel field value not triggering save

### ISSUE THREAD

**Issue by prestop-max** [Dulajdeshan/strapi-advanced-uuid#29]
The uuid generation fills the field but does not trigger the onChange not allowing for the value to be saved.

As a result for not allowing field input manipulation directly, combined with regexp limitations and uuid generation on null values creates a situation where you are stuck on alot of situations.

**Comment by miikee-us** [comment]
I think I'm having the same issue.

When creating a new entry, the generated UUID based on Regex shows correctly:

<img width="791" alt="Screen Shot 2023-09-12 at 8 31 32 PM" src="https://github.com/Dulajdeshan/strapi-advanced-uuid/assets/27359863/180e50a4-df57-4194-9001-30af28cbe68b">

When I click save, it saves with the wrong format. To correct it, I have to click the refresh icon then save again. 

<img width="812" alt="Screen Shot 2023-09-12 at 8 34 00 PM" src="https://github.com/Dulajdeshan/strapi-advanced-uuid/assets/27359863/69f52cbd-89a0-4e6b-a1a8-47cd729e2c81">
