### ISSUE TITLE
Question about uniqueness 

### ISSUE THREAD

**Issue by mbaev** [Dulajdeshan/strapi-advanced-uuid#45]
Hi @Dulajdeshan,

Thank you for the awesome plugin! It very easy to use and does its work perfectly!

I've a question which I couldn't find answer for.
Sorry if there was one, but can this plugin be configured to keep unique values only so I can use the value as identifier?

Thank you

**Comment by mbaev** [comment]
Oh, I'm sorry. I spent an hour searching for info about uniqueness and even looked at the code (don't have enough experience to understand that ¯\_(ツ)_/¯). Once I've created the issue in very same minute found:
> The Strapi Advanced UUID Plugin is a custom plugin for Strapi that automatically generates a unique UUID for your content. It also allows you to generate UUID based on your regular expressions.

Can you confirm that?
> generates a unique UUID

Thank you

**Comment by Dulajdeshan** [comment]
Hi @mbaev  thanks for your feeback.

Yes, using this plugin you can generate a unique value (id) for your field. If you configure a custom regex, plugin will generate the id based on that regex, unless it will generate using UUID V4.

**Comment by mbaev** [comment]
Perfect! Thank you!
Hope someone will find this issue helpful =)
