### ISSUE TITLE
Question regarding regenerate button

### ISSUE THREAD

**Issue by Intentivekhansen** [Dulajdeshan/strapi-advanced-uuid#46]
Hi there!

in the admin UI the UUID field is displayed with a regenerate button for the UUID on the field.  This button is also displayed if the field itself is disabled.

For our usecase we would require to disable this regenerate option in the UI as we only want the UUID to be auto generated on component creation or if the value itself is set via API. We would require that once the UUID is set on a component it is not possible to change it again via admin UI. 

Is there currenty an option to achieve this?

Thanks in advance! If there is anything unclear, just let me know!

**Comment by Dulajdeshan** [comment]
> Hi there!
> 
> in the admin UI the UUID field is displayed with a regenerate button for the UUID on the field. This button is also displayed if the field itself is disabled.
> 
> For our usecase we would require to disable this regenerate option in the UI as we only want the UUID to be auto generated on component creation or if the value itself is set via API. We would require that once the UUID is set on a component it is not possible to change it again via admin UI.
> 
> Is there currenty an option to achieve this?
> 
> Thanks in advance! If there is anything unclear, just let me know!

Thanks for your feedback. Currently there's no option to achieve this. I'll work on this feature enhancement.

**Comment by Intentivekhansen** [comment]
Thanks, works great! :)
