### ISSUE TITLE
Type a UID instead of just generate it.

### ISSUE THREAD

**Issue by adrknapp** [Dulajdeshan/strapi-advanced-uuid#55]
Hello! I'm facing a big issue here.

I'm migrating a huge database to my Strapi, but I need to keep our old UIDs, there is a way to enable write on the UID field, instead of just generating it automatically? If I could just copy and paste our old IDs on the field, would save my life lol. @Dulajdeshan

**Comment by etekweb** [comment]
+1 for this - would be very nice to have an editable option for the UUID field, instead of just regenerate.

**Comment by Dulajdeshan** [comment]
Hi @etekweb @adrknapp I have added an option to disable auto generation of UUID. Hope it will solve your issues.

Happy Coding 😃 !!
