### ISSUE TITLE
Support for strapi@5

### ISSUE THREAD

**Issue by monolithed** [Dulajdeshan/strapi-advanced-uuid#59]
```
➜ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @strapi/strapi@5.0.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"5.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.14.5" from strapi-advanced-uuid@1.3.0
npm ERR! node_modules/strapi-advanced-uuid
npm ERR!   strapi-advanced-uuid@"1.3.0" from the root project
npm ERR! 
```

**Comment by 320dr** [comment]
![1](https://github.com/user-attachments/assets/a473dffd-f22b-476f-94de-c21a308b7180)

Running "yarn add strapi-advanced-uuid" can be successfully installed, but running "yarn develop" / "yarn build" to start STRAPI5 will result in an error.

**Comment by joseOlivares** [comment]
I have the same issue upgrading from strapi 4 to 5
![Error strapi](https://github.com/user-attachments/assets/52e83aad-840b-476d-8ac2-2945e598705a)

**Comment by nickwph** [comment]
we are waiting here too! 😄

**Comment by tmm42** [comment]
> we are waiting here too! 😄 
> 
> doing this for now `npm install -S Dulajdeshan/strapi-advanced-uuid#59-support-for-strapi5`

Nice, I can install the plugin with Strapi 5, but it doesn't appear in the custom fields section. 

Any idea how I can solve that?

**Comment by monolithed** [comment]
Honestly, after switching to version 5, I no longer needed to pass UUIDs because there are already unique documentIds available. Hopefully, this helps someone
