### ISSUE TITLE
UUID changes when calling entity service update

### ISSUE THREAD

**Issue by krissy** [Dulajdeshan/strapi-advanced-uuid#64]
Hi there! 

I've added a UUID to my user permissions model, but when I update the record in my plugin extension, I noticed it's changing the UUID, despite it not being one of the specified fields to change. 🫣

```
const newData = _.pick(data, [
  'newsletter',
]);

await strapi.entityService.update('plugin::users-permissions.user', user.id, {
  data: newData      
}).then((res) => {
  ctx.response.status = 200;
})
```

Currently on Strapi v4.25.2. I have autofill enabled on the custom field, but I assume that should only ever work on a new record. Please help asap!

**Comment by shommey** [comment]
This exact issue persists even in 2.1.1, no matter how the entity is updated (REST api, programmatically or via admin UI) the UUID gets regenerated.
